### ISSUE TITLE
Widget not loading

### ISSUE THREAD

**Issue by puecher** [werstreamtes/pimcore-list-widget#1]
Hi,

the widget shows the following error message: "Leider ist beim Laden der Daten ein Fehler aufgetreten.".

https://github.com/werstreamtes/pimcore-list-widget/blob/main/src/Resources/views/Areas/list-widget/view.html.twig#L15 opens https://www.werstreamt.es/widgets/filter/embed/?filterUrl= (404 error code). There may be a new embed code using https://www.werstreamt.es/_resources/themes/wse/js/widget.v4.min.js.

**Comment by actionandy** [comment]
Hello,
did you add a filter URL in the settings after adding the block?
It could be https://www.werstreamt.es/filme/ or https://www.werstreamt.es/serien/ for example.

**Comment by puecher** [comment]
Cool, thank you, this did the trick!

I was using https://www.werstreamt.es/film/details/45858/harry-potter-und-der-stein-der-weisen/.
